### PR TITLE
Workaround to allow buildpack install from github

### PR DESCRIPTION
**Pull request by troytop**
Fixes:
Error: Expected a buildpack, did not find bin/compile inside /tmp/stackato-buildpack-7Bc55Var2y.zip

### CODE REVIEW

**Comment by troytop** [comment]
@jandubois points out:

> And what happens on Windows?  You may end up with a file that contains just the name of the target
> So if you then invoke it as a bash script in the stager, it could fail.
> It should be fine, because bin/compile will only be called on Linux stager, which should never happen, because bin/detect doesn't exist

**Comment by jandubois** [comment]
Just create a 0-byte file for bin/compile, and you can install the buildpack with

```
stackato create-buildpack dotnet https://github.com/hpcloud/cf-iis8-buildpack/archive/1.3.0.15.zip
```

The `bin/compile` is needed by the client to determine how many top level directories to strip away so that the `bin/` directory ends up at the top.

**Comment by florindragos** [comment]
The bin/compile file does not affect the windows staging process. As long as it does not have a windows executable extension, is is being ignored.

**Comment by jandubois** [comment]
> The bin/compile file does not affect the windows staging process. As long as it does not have a windows executable extension, is is being ignored.

Yes, that is exactly what we want. It only needs to be there to be installable by the client. I haven't tested it recently, but I think the `cf create-buildpack` command has the same requirement.

BTW, it would be good to also have a `bin/detect` script for Unix that simply contains

```
exit 1
```

It would be ignored on Windows (no file extension) and would tell the Linux DEA that it can't handle _any_ app. That way you don't get a distracting warning when pushing Unix apps that don't explicitly specify a buildpack:

```
staging: -----> Downloaded app package (204K)
staging: Failed to run buildpack detection script with error: No such file or directory - /tmp/dea_ng/admin_buildpacks/63a2609e-1e55-44b7-8e6d-15b73157d7cc_93194ffe6c203ae226918c2a902ca907dae7eaec/bin/detect /tmp/staged/app
staging: -------> Buildpack version 1.2.1
```

This is especially confusing because it doesn't say (in human readable terms) which buildpack was missing the bin/detect script.

**Comment by jandubois** [comment]
Replaced by https://github.com/hpcloud/cf-iis8-buildpack/pull/3 which contains the discussed changes in a merge-able state.

**Pull request closed without merging**
